In [24]:
# KNN
vizinhos = 3

In [1]:
# Importando as Bibliotecas Básicas
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# Importando a Biblioteca do KNN
from sklearn.neighbors import KNeighborsClassifier
# Importando a Biblioteca de Acurácia, Matriz de Confusão (em quantos jogos entrou em quantos foi green ou red)
from sklearn.metrics import accuracy_score, confusion_matrix
# Importando a Biblioteca SkLearn para padronizar os dados (entre 0 e 1)
from sklearn.preprocessing import StandardScaler
# Importando a Biblioteca SkLearn para dividir os dados entre treinamento e teste
from sklearn.model_selection import train_test_split

In [6]:
# Importando os DataFrames

# England Premier League
df_ENG1 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/England%20Premier%20League_20212022.xlsx?raw=true')
# England Championship
df_ENG2 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/England%20Championship_20212022.xlsx?raw=true')

# France Ligue 1
df_FRA1 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/France%20Ligue%201_20212022.xlsx?raw=true')
# France Ligue 2
df_FRA2 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/France%20Ligue%202_20212022.xlsx?raw=true')

# Germany Bundesliga
df_GER1 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Germany%20Bundesliga_20212022.xlsx?raw=true')
# Germany 2. Bundesliga
df_GER2 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Germany%202.%20Bundesliga_20212022.xlsx?raw=true')

# Italy Serie A
df_ITA1 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Italy%20Serie%20A_20212022.xlsx?raw=true')
# Italy Serie B
df_ITA2 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Italy%20Serie%20B_20212022.xlsx?raw=true')

# Spain La Liga
df_SPA1 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Spain%20La%20Liga_20212022.xlsx?raw=true')
# Spain Segunda División
df_SPA2 = pd.read_excel('https://github.com/futpythontrader/YouTube/blob/main/Spain%20Segunda%20Divisi%C3%B3n_20212022.xlsx?raw=true')

# Concatenando os DataFrames
df = [df_ENG1,df_ENG2,df_FRA1,df_FRA2,df_GER1,df_GER2,df_ITA1,df_ITA1,df_SPA1,df_SPA2]
df = pd.concat(df)
df = df[['Home','Away','FT_Odds_H','FT_Odds_D','FT_Odds_A','FT_Odds_Over05','FT_Odds_Over15','FT_Odds_Over25','FT_Odds_BTTS_Yes','FT_Goals_H','FT_Goals_A']]

In [7]:
# Criando a Coluna de 0 e 1 para análise do Modelo de Machine Learning
df.loc[(df['FT_Goals_H'] > df['FT_Goals_A']), 'BackHome'] = 1
df.loc[(df['FT_Goals_H'] <= df['FT_Goals_A']), 'BackHome'] = 0

In [8]:
df


Home                    Away  FT_Odds_H  FT_Odds_D  \
0            Brentford                 Arsenal       3.90       3.40   
1    Manchester United            Leeds United       1.62       4.15   
2              Burnley  Brighton & Hove Albion       3.20       3.00   
3              Chelsea          Crystal Palace       1.27       5.40   
4              Everton             Southampton       1.84       3.65   
..                 ...                     ...        ...        ...   
463          Girona FC                SD Eibar       2.25       3.25   
464      UD Las Palmas             CD Tenerife       1.91       3.20   
465           SD Eibar               Girona FC       2.37       3.25   
466          Girona FC             CD Tenerife       2.10       3.20   
467        CD Tenerife               Girona FC       2.20       2.92   

     FT_Odds_A  FT_Odds_Over05  FT_Odds_Over15  FT_Odds_Over25  \
0         2.05            1.11            1.43            2.20   
1         5.25            1.06            1.25            1.69   
2         2.31            1.14            1.43            2.35   
3         9.40            1.09            1.40            1.67   
4         3.85            1.12            1.47            1.85   
..         ...             ...             ...             ...   
463       3.15            1.08            1.40            2.12   
464       3.75            1.04            1.39            2.10   
465       3.15            1.08            1.40            2.20   
466       3.85            1.11            1.53            2.35   
467       2.82            1.11            1.62            2.60   

     FT_Odds_BTTS_Yes  FT_Goals_H  FT_Goals_A  BackHome  
0                1.95           2           0       1.0  
1                1.71           5           1       1.0  
2                2.10           1           2       0.0  
3                2.65           3           0       1.0  
4                2.10           3           1       1.0  
..                ...         ...         ...       ...  
463              1.91           0           1       0.0  
464              1.99           1           2       0.0  
465              1.91           0           2       0.0  
466              2.10           0           0       0.0  
467              2.15           1           3       0.0  

[3919 rows x 12 columns]

In [9]:
df1 = df[['Home','Away','FT_Odds_H','FT_Odds_D','FT_Odds_A','FT_Odds_Over05','FT_Odds_Over15','FT_Odds_Over25','FT_Odds_BTTS_Yes','BackHome']]
df2 = df[['FT_Odds_H','FT_Odds_D','FT_Odds_A','FT_Odds_Over05','FT_Odds_Over15','FT_Odds_Over25','FT_Odds_BTTS_Yes','BackHome']]

In [10]:
df1 = df1.dropna()
# convertendo os arrays (matriz)
# definindo qual coluna é a entrada e qual é a saída
df1_x = df1.iloc[:,0:10].values

# separando os dados para treino e para teste
x_dados_treinamento, x_dados_teste = train_test_split(df1_x, test_size=0.20, random_state = 0)

df1 = pd.DataFrame(x_dados_teste)
df1.columns = ['Home','Away','FT_Odds_H','FT_Odds_D','FT_Odds_A','FT_Odds_Over05','FT_Odds_Over15','FT_Odds_Over25','FT_Odds_BTTS_Yes','BackHome']

In [11]:
df2 = df2.dropna()
# convertendo os arrays (matriz)
# definindo qual coluna é a entrada e qual é a saída
df2_x = df2.iloc[:,0:7].values
df2_y = df2.iloc[:,7].values

In [13]:
df2_x

array([[3.9 , 3.4 , 2.05, ..., 1.43, 2.2 , 1.95],
       [1.62, 4.15, 5.25, ..., 1.25, 1.69, 1.71],
       [3.2 , 3.  , 2.31, ..., 1.43, 2.35, 2.1 ],
       ...,
       [2.37, 3.25, 3.15, ..., 1.4 , 2.2 , 1.91],
       [2.1 , 3.2 , 3.85, ..., 1.53, 2.35, 2.1 ],
       [2.2 , 2.92, 2.82, ..., 1.62, 2.6 , 2.15]])

In [15]:
df2_y

array([1., 1., 0., ..., 0., 0., 0.])

In [16]:
# padronizando os dados de entrada
scaler_goals = StandardScaler()
df2_x = scaler_goals.fit_transform(df2_x)

In [17]:
# separando os dados para treino e para teste
x_dados_treinamento, x_dados_teste, y_dados_treinamento, y_dados_teste = train_test_split(df2_x, df2_y, test_size=0.20, random_state = 0)

In [25]:
# Definições de Parâmetros e dados de entrada e resultado para treinamento
knn_dados = KNeighborsClassifier(n_neighbors=vizinhos, metric="minkowski", p=2)
knn_dados.fit(x_dados_treinamento, y_dados_treinamento)

KNeighborsClassifier(n_neighbors=3)

In [26]:
# Previsões
previsoes_knn = knn_dados.predict(x_dados_teste)

In [27]:
# taxa de acerto
accuracy_score(y_dados_teste, previsoes_knn)

0.6301020408163265

In [28]:
# matriz de confusão
confusion_matrix(y_dados_teste, previsoes_knn)
# a11 = coisas que ele preveu como sendo 0 e foi 0 (312 jogos ele preveu que não seria H e não foi H) 
# a21 = coisas que ele preveu como sendo 0 e foi 1 (165 jogos ele preveu que não seria H e foi H)
# a12 = coisas que ele preveu como sendo 1 e foi 0 (125 jogos ele preveu que seria H e não foi H)
# a22 = coisas que ele preveu como sendo 1 e foi 1 (182 jogos ele preveu que seria H e foi H)

array([[312, 125],
       [165, 182]], dtype=int64)

In [29]:
# jogos totais usados para teste
jogos_total_teste = confusion_matrix(y_dados_teste, previsoes_knn)[0][0]+confusion_matrix(y_dados_teste, previsoes_knn)[0][1]+confusion_matrix(y_dados_teste, previsoes_knn)[1][0]++confusion_matrix(y_dados_teste, previsoes_knn)[1][1]
jogos_total_teste

784

In [30]:
# quantidade total de entrada
jogos_entrada = confusion_matrix(y_dados_teste, previsoes_knn)[0][1]+confusion_matrix(y_dados_teste, previsoes_knn)[1][1]
jogos_entrada

307

In [32]:
# calculando a taxa de entrada
taxa_de_entrada = (jogos_entrada/jogos_total_teste)*100
taxa_de_entrada

39.15816326530612

In [33]:
# calculando a taxa de acerto
taxa_de_acerto = (confusion_matrix(y_dados_teste, previsoes_knn)[1][1]/jogos_entrada)*100
taxa_de_acerto

59.28338762214984

In [34]:
df1["Previsões"] = previsoes_knn

In [35]:
stake = 1
win_Back = stake * (df1.FT_Odds_H - 1)
lose_Back = -stake

df1.loc[(df1['Previsões'] == 1) & (df1['BackHome'] == 1), 'Profit'] = win_Back
df1.loc[(df1['Previsões'] == 1) & (df1['BackHome'] == 0), 'Profit'] = lose_Back
df1.loc[(df1['Previsões'] == 0) & (df1['BackHome'] == 1), 'Profit'] = 0
df1.loc[(df1['Previsões'] == 0) & (df1['BackHome'] == 0), 'Profit'] = 0

filtro = df1.Previsões == 1
df0 = df1[filtro]

# Ajustando o Índice
df0.reset_index(inplace=True, drop=True)
df0.index = df0.index.set_names(['Nº'])
df0 = df0.rename(index=lambda x: x + 1)

df0['Profit_acu'] = df0.Profit.cumsum()
df0.Profit_acu.plot()
df0.Profit_acu.tail(1)

Nº
307    22.3
Name: Profit_acu, dtype: object

In [36]:
ROI = df0.Profit_acu.tail(1)/len(df0)*100
ROI

Nº
307    7.263844
Name: Profit_acu, dtype: object

In [37]:
# Verificando um Jogo Específico
FT_Odds_H = input("Digite a Odd do Mandante: ")
FT_Odds_A = input("Digite a Odd do Visitante: ")
FT_Odds_D = input("Digite a Odd do Empate: ")
FT_Odds_Over05 = input("Digite a Odd do Over05: ")
FT_Odds_Over15 = input("Digite a Odd do Over15: ")
FT_Odds_Over25 = input("Digite a Odd do Over25: ")
FT_Odds_BTTS_Yes = input("Digite a Odd do BTTS: ")

Odds = [FT_Odds_H,FT_Odds_A,FT_Odds_D,FT_Odds_Over05,FT_Odds_Over15,FT_Odds_Over25,FT_Odds_BTTS_Yes]

# Transformando a Lista em uma Matriz
odds_jogo = np.array(Odds)

previsao_jogo_knn = odds_jogo.reshape(1, -1)
previsao_jogo_knn = knn_dados.predict(previsao_jogo_knn)

if previsao_jogo_knn == 1:
  print('');print("Fazer Back Mandante")
else:
  print('');print("Ficar de Fora desse jogo")    

Digite a Odd do Mandante: 2.50
Digite a Odd do Visitante: 3.40
Digite a Odd do Empate: 2.62
Digite a Odd do Over05: 1.16
Digite a Odd do Over15: 1.61
Digite a Odd do Over25: 3.00
Digite a Odd do BTTS: 2.50

Fazer Back Mandante
